### ISSUE TITLE
Refactor the DialogComponent to be more general use

### ISSUE THREAD

**Issue by boris-dp** [Ziriax/sts-weather#4]
> Zou je deze component algemener kunnen maken? Dus niet specifiek voor het vragen van een city, maar eender welke tekst? Dus echt een `prompt` vervangen?
> 
> De `readonly getWeatherAsync: (city: string) => void;` kan je dan vervangen door een `onText(value: string): void`
> 
> Eventueel kan je ook een `onCancel?(): void` toevoegen, alsook de tekst die in de `ok` knop moet komen?
> 
> Je zou er ook ipv een component er een custom hook van kunnen maken, bvb `usePrompt`, een beetje [zoals deze](https://www.npmjs.com/package/react-alert), maar dat hoeft nu niet

_Originally posted by @Ziriax in https://github.com/Ziriax/sts-weather/pull/1#discussion_r597050906_

**Comment by boris-dp** [comment]
Ik weet niet zeker of een hook maken hiervoor interessant zou zijn. Ik denk dat u bedoelde om dit voor de alerts te maken, maar ik ben niet zeker of u dit ook graag wilt voor het dialog component. Voor de alerts zie ik er wel zeker het nut van in.

**Comment by ziriax** [comment]
Inderdaad, voor alert kan een hook nuttig zijn, voor prompt ben ik er zelf
nog niet uit...
